In [6]:
import numpy as np

In [7]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [8]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [9]:
type(arr1)

numpy.ndarray

# nd = n-dimensional

In [12]:
arr2 = np.arange(10,20,1) # (start, stop (non-inclusive), step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
list1

[10, 20, 30]

In [14]:
list2 = [40, 50, 60]

In [15]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

## arr3 = np.array(list3)


arr3

In [18]:
arr3.shape

(2, 3)

In [27]:
arr3dim = np.array(
    [[1,2,3],[3,4,5]],
    [[5,6,7],[8,9,1]]
)
arr3dim

TypeError: Field elements must be 2- or 3-tuples, got '[5, 6, 7]'

In [20]:
## matrix operations

In [21]:
list1

[10, 20, 30]

In [22]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [23]:
arr3dim * 3

NameError: name 'arr3dim' is not defined

In [24]:
arr1 = np.array(list2)

In [25]:
arr1

array([40, 50, 60])

In [30]:
## lab
arr12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
arr2d.shape

(3, 4)

In [37]:
arr3d = np.array([
    [[1,2,3,4], [5,6,7,8],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[100,234,35,44], [57,69,7,8],[1,2,3,4],[1,2,3,4],[1,2,3,4]]    
])
arr3d.shape

(2, 5, 4)

In [39]:
np.zeros((12,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,5,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [42]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
arr1 = [1,2,3]

In [46]:
arr1[2]

3

In [47]:
arr3 = np.array([[10,20,30],[40,50,60]])

In [48]:
arr3[1,2]

60

In [49]:
arr3[1][2]

60

In [50]:
arr3[0]

array([10, 20, 30])

In [51]:
arr3[:,1]

array([20, 50])

In [52]:
arr3dim

NameError: name 'arr3dim' is not defined

In [53]:
arr3d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4]],

       [[100, 234,  35,  44],
        [ 57,  69,   7,   8],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4]]])

In [54]:
arr3d[2,0,3]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [55]:
arr3d[1,0,3]

44

In [56]:
arr3d[:,:,1]

array([[  2,   6,   2,   2,   2],
       [234,  69,   2,   2,   2]])

In [57]:
arr3d.sum()

650

In [58]:
arr3d.mean()

16.25

In [59]:
arr3d.std()

40.57754921135578

In [60]:
arr3d.mean(0)

array([[ 50.5, 118. ,  19. ,  24. ],
       [ 31. ,  37.5,   7. ,   8. ],
       [  1. ,   2. ,   3. ,   4. ],
       [  1. ,   2. ,   3. ,   4. ],
       [  1. ,   2. ,   3. ,   4. ]])

In [61]:
arr3d.mean(1)

array([[ 1.8,  2.8,  3.8,  4.8],
       [32. , 61.8, 10.2, 12.8]])

In [62]:
arr3d.mean(2)

array([[  2.5 ,   6.5 ,   2.5 ,   2.5 ,   2.5 ],
       [103.25,  35.25,   2.5 ,   2.5 ,   2.5 ]])

In [63]:
arr3d.var()

1646.5375

In [64]:
arr3d.min()

1

In [65]:
arr3d.max()

234

In [66]:
for x in arr1:
    print(x)

1
2
3


In [67]:
for dim in arr3d:
    print(dim)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[100 234  35  44]
 [ 57  69   7   8]
 [  1   2   3   4]
 [  1   2   3   4]
 [  1   2   3   4]]


In [68]:
for x in np.nditer(arr3d):
    print(x)

1
2
3
4
5
6
7
8
1
2
3
4
1
2
3
4
1
2
3
4
100
234
35
44
57
69
7
8
1
2
3
4
1
2
3
4
1
2
3
4


In [69]:
np.save("new_array", arr3d)

In [70]:
np.load("new_array.npy")

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4]],

       [[100, 234,  35,  44],
        [ 57,  69,   7,   8],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4],
        [  1,   2,   3,   4]]])

In [72]:
np.savetxt("new_array.txt", arr1, delimiter='\t')

In [73]:
np.loadtxt("new_array.txt", delimiter='\t')

array([1., 2., 3.])